openapi: 3.0.1
info:
  version: 1.0.0
  title: '${title}'
  description: '${description}'
  contact:
    email: tern@uq.com.au
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    OpenID:
      type: openIdConnect
      openIdConnectUrl: >-
        https://auth-test.tern.org.au/auth/realms/local/.well-known/openid-configuration
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - BasicAuth: []
  - BearerAuth: []
  - OpenID: []
  - ApiKeyAuth: []
tags: []
paths:
  /slurm:
    parameters:
      - name: endpoint
        in: path
        description: Fetch and execute different commands available for slurm
        required: true
        schema:
          type: string
          enum:
            - exists
            - projects
            - usage
            - stop_process
            - start_server
            - list_all
            - exec_host
            - running
            - accesstoken
            - end_session
            - preference
            - session_info
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: Execute host
      description: Execute host
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /vnc:
    parameters:
      - name: endpoint
        in: path
        description: Fetch and execute different commands available for slurm
        required: true
        schema:
          type: string
          enum:
            - display
            - opt
            - start_tunnel
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: display vnc data
      description: display vnc data
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /group:
    parameters:
      - name: endpoint
        in: path
        description: Fetch and execute different commands available for group
        required: true
        schema:
          type: string
          enum:
            - projects
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: group projects
      description: group projects
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error

