openapi: 3.0.1
info:
  version: 1.0.0
  title: '${title}'
  description: '${description}'
  contact:
    email: tern@uq.com.au
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    OpenID:
      type: openIdConnect
      openIdConnectUrl: >-
        https://auth-test.tern.org.au/auth/realms/local/.well-known/openid-configuration
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - BasicAuth: []
  - BearerAuth: []
  - OpenID: []
  - ApiKeyAuth: []
tags: []
paths:
  /example:
    $ref: ./token/index.yml
  /example/testing:
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    post:
      summary: Verify key signatures
      description: Verify that public key was used to sing the cert key.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                variale_1: Example of any variables that you will provide
                variable_2: Example of any other variable
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /slurm/sessioninfo:
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: Slurm session info
      description: Slurm session info
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /slurm/accesstoken:
    $ref: ./slurm/access_token.yml
  /slurm/endsession:
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: Finalised user session with the remote job
      description: Finalised user session with the remote job
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /slurm/preference:
    $ref: ./slurm/preference.yml
  /slurm/exists:
    ptions:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: Check if user exists
      description: Check if user exists in the virtual machine or LDAP
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /slurm/projects:
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: Get all projects
      description: Get slurm projects
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /slurm/usage:
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: Check usage
      description: Check usage
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /slurm/stopprocess:
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: Stop slurm job
      description: Stop slurm job
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /slurm/startserver:
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: Start server
      description: Start slurm job
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /slurm/listall:
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: List all
      description: List all jobs running
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /slurm/exechost:
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: Execute host
      description: Execute host
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /vnc/display:
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: display vnc data
      description: display vnc data
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /vnc/otp:
    options:
      summary: Request options
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                title: Empty Schema
                type: object
    get:
      summary: opt
      description: opt
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Forbidden
        '401':
          description: Unauthorized
        '403':
          description: Bad Request
        '500':
          description: Internal Server Error
  /slurm/running:
    $ref: ./slurm/running.yml
  /group/projects:
    $ref: ./group/projects.yml

